### ISSUE TITLE
No continuous post

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/MIYUKKI-Direct#10]
連投禁止。
最低5分以上開けるように（From dj.life-is-tech.com）。

**Comment by ygkn** [comment]
連投あかんかったのか

**Comment by mizucoffee** [comment]
一応公式DJ MIYUKKIでは制限かけられてる。
...しっかし前まで10分だった気がするんだけどなぁ...

**Comment by ygkn** [comment]
一回投稿したら5分間投稿できないって感じでおk？

**Comment by mizucoffee** [comment]
:+1:
