### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/MIYUKKI-Direct#11]
少しずつやる。。。かも。

**Comment by ygkn** [comment]
全く別な感じになるから新しいリポジトリ作ったほうがいいと思うー

**Comment by ygkn** [comment]
Write once, Run Anywhere.とはいかない

**Comment by mizucoffee** [comment]
そんなに違うん？
ブランチ切って流用しようかと思ってたけど。。。

**Comment by mizucoffee** [comment]
非サポートのAPIを代用すりゃ動くかと思ってた（甘い

**Comment by ygkn** [comment]
これ[Git Flow](http://danielkummer.github.io/git-flow-cheatsheet/index.ja_JP.html)で運用してるからブランチ切るのはやめといたほうがいいんじゃないかな。
僕もちょっと調べてみたけどファイル構成からして結構ちがうみたいよ。

**Comment by mizucoffee** [comment]
まっじかー
WebExtension意味ねええ（）
じゃあ分けてかなー

**Comment by mizucoffee** [comment]
でもファイル構成はほぼまんまだったような気もする（てか統一規格じゃ

**Comment by ygkn** [comment]
WebExtension使うんだったら、

- chrome.storage (localstorageで代用可)
- identity（ライブラリ噛ませて代用）

だけでいけるな。

あとはFetch APIとかの互換性かなー

**Comment by ygkn** [comment]
だとしてもブランチ分けじゃなくてフォークしたほうがいいと思うけど……

**Comment by mizucoffee** [comment]
だよねー
やりようはあるけどflow使ってるならリポ切ってアプデのときにPRして取り込むかな

**Comment by mizucoffee** [comment]
PRじゃないな
なんか取り込むのあったよね、それ（）

**Comment by ygkn** [comment]
あーCSSの

- スクロールバー
- はみ出たとこを…ってする

がwebkit専用だー。

なんかで代用できると思うけど……

**Comment by mizucoffee** [comment]
まあそのへんは臨機応変になんとか（）

**Comment by mizucoffee** [comment]
Chrome勢に戻ってしまった...
まあ移行だけしちゃっても良いけど...

**Comment by mizucoffee** [comment]
か　ー　な　ー　し　ー　み　ー　の　ー
　　む　ー　こ　ー　お　ー　へ　ー　と　ー
