### ISSUE TITLE
Twitter OAuth

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/MIYUKKI-Direct#7]
## Description
Twitterとの連携機能を付けてDJシステムに投稿したら自動的にTwitterにも投稿されるように。
\#dj_miyukki_room_idみたいなハッシュタグ付けたら面白いかも。

### Example
> DJ MIYUKKI SYSTEMにXXXを投稿しました！ 
> http://www.example.com/
> 
> #dj_miyukki_room_id

これは全然必須性無いので気が向いたらおなしゃす。

**Comment by ygkn** [comment]
なにそれ面白い。
考えとくー

**Comment by mizucoffee** [comment]
JS無知だけど火狐勢だし気が向いたら火狐版作ろうかなぁ...
といっても3月くらいまでずっと忙しそうだけど（）

#11

**Comment by ygkn** [comment]
結構簡単にできるかもしれん。
chromeのユーザー認証系APIが神ってる。（なおFirefoxとの互換は……）

**Comment by ygkn** [comment]
あ、APIじゃなくて普通にシェアボタンみたいにしたらいいのか（）

**Comment by ygkn** [comment]
いけたいけts()

**Comment by ygkn** [comment]
:tada:   v1.2.2 で対応しました！ :sparkles:
