### ISSUE TITLE
Now Playing

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/MIYUKKI-Direct#8]
https://dj.life-is-tech.com/js/submit.js
このソースの上から10行位で現在再生中を取得してる感。
Firebaseを叩けるなら是非欲しい機能。

**Comment by ygkn** [comment]
認証情報とかが分からない……
何か情報持ってます？

かくなる上はスクレイピング？（）

**Comment by mizucoffee** [comment]
Firebaseとdjのフロントはほぼ間違いなく別だからどこかにその情報があるはず...?
探さねば。

**Comment by mizucoffee** [comment]
https://dj.life-is-tech.com/js/config.js

**Comment by mizucoffee** [comment]
```
var ref = new Firebase([FIREBASE_URL, "rooms", getRoomId(), "playing"].join("/"));
```
行けそう？

**Comment by ygkn** [comment]
それはもう見つけたー
今検証中

**Comment by ygkn** [comment]
Now Playing 取れたら通知とか送ってみたい

**Comment by mizucoffee** [comment]
なにそれ便利

**Comment by ygkn** [comment]
https://jsfiddle.net/xhhjdzsz/4/

検証用

**Comment by ygkn** [comment]
Firebase 3.3.0

https://jsfiddle.net/xhhjdzsz/5/

**Comment by mizucoffee** [comment]
取れてることを祈るのみ

**Comment by ygkn** [comment]
キャンプ始まったらすぐに実装できるようにしときます

**Comment by ygkn** [comment]
現在`develop`ブランチにおいてNowPlaying機能使えます。
データ構造がわからないので表示がどうなるか予測がつきませんが…。

**Comment by ygkn** [comment]
かなしみ

**Comment by mizucoffee** [comment]
今までありがとう
